FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY ./shared ../shared

RUN npm install

# Copy source code
COPY src ./src
COPY tsconfig.json ./

# For development: use nodemon
EXPOSE 4000

CMD ["npm", "run", "dev"]
